title: "Flash Deals Amazon"
email: imvjerry96@gmail.com
description: "Cập nhật Flash Deals, Hot Deals mới nhất từ Amazon"
baseurl: "/"   # Use "/" for the root
url: "http://wowzarush.com"
twitter_username: VietAthen
github_username: VATHEN96

theme: minima
paginate: 10

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
