# Welcome to Jekyll!

# Site settings
title: wowzarush
email: imvjerry96@gmail.com
description: >- 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""  # the subpath of your site, e.g. /blog
url: "http://wowzarush.com"
twitter_username: VietAthen
github_username: VATHEN96

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# These items will not be processed by default.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
