# Wrangler configuration for Cloudflare Pages
name = "wowzarush"
compatibility_date = "2023-12-01"

# Pages configuration
[site]
bucket = ".next/static"

[build]
command = "npm run build"
output_directory = ".next"

[env.production]
pages_build_output_dir = ".next"

[env.preview]
pages_build_output_dir = ".next"

# Disable TypeScript checking during build to allow deployment
# We'll handle TypeScript errors separately
[build.environment]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
