# Simple Cloudflare Pages configuration
name = "wowzarush"
compatibility_date = "2023-12-01"

# Command to run
[build]
command = "node build-cf.js"

# Output directory
[site]
bucket = ".next"

# Pages build output directory
[build.upload]
format = "directory"

# Environment settings
[env.production]
pages_build_output_dir = ".next"

[env.preview]
pages_build_output_dir = ".next"
