# Wrangler configuration for Cloudflare Pages
name = "wowzarush"
compatibility_date = "2023-12-01"

# Build output configuration
[build]
command = "npm run cloudflare-build"

[build.environment]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"

# Pages specific configuration
[site]
bucket = ".next"

# This is the key property Cloudflare Pages is looking for
[build.upload]
format = "directory"

# Environment-specific configurations
[env.production]
pages_build_output_dir = ".next"

[env.preview]
pages_build_output_dir = ".next"
